name: cloudinary_client
description: >
  dart wrapper for cloudinary image apis. Right now only supports image upload.
  Will be extended to support other media type as well.
version: 0.1.0
homepage: https://github.com/r4jiv007/CloudinaryClient

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  http: ^0.13.3

  #crypto
  crypto: ^3.0.1

dev_dependencies:
  flutter_lints: ^1.0.4