name: cloudinary_client
description: >
  dart wrapper for cloudinary image apis. Right now only supports image upload.
  Will be extended to support other media type as well.

version: 0.1.0
author: Rajiv Singh <r4jiv008@gmail.com>
homepage: https://github.com/r4jiv007/CloudinaryClient

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3

  #crypto
  crypto: ^3.0.1

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec